### ISSUE TITLE
wasmedge echo hangs on second execution

### ISSUE THREAD

**Issue by devigned** [containerd/runwasi#70] opened 2023-02-21 21:09 UTC
To repro run the following:

```shell
sudo ctr run --rm --runtime=io.containerd.wasmedge.v1 ghcr.io/containerd/runwasi/wasi-demo-app:latest testwasm /wasi-demo-app.wasm echo 'hello'
hello
exiting
sudo ctr run --rm --runtime=io.containerd.wasmedge.v1 ghcr.io/containerd/runwasi/wasi-demo-app:latest testwasm /wasi-demo-app.wasm echo 'hello'
hello
exiting
# hangs here
```

**Comment by rumpl** [comment] 2023-02-21 21:42
@devigned I have not, can you point me to the source code of that image please? Trying to run this with docker gives me an error

```console
$ docker pull ghcr.io/containerd/runwasi/wasi-demo-app:latest
Error response from daemon: failed to resolve reference "ghcr.io/containerd/runwasi/wasi-demo-app:latest": failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```

**Comment by rumpl** [comment] 2023-02-21 21:43
@CaptainVincent

**Comment by rumpl** [comment] 2023-02-21 21:52
@devigned can you try with `--runtime=io.containerd.wasmedge.v1 --platform=wasi/wasm secondstate/rust-example-hello:latest`, I just tried it with `docker run` and it doesn't hang

**Comment by devigned** [comment] 2023-02-21 21:57
This issue didn't come from me, but someone that reached out via slack. I'm going to encourage them to post the code & image.

**Comment by sboett-dev** [comment] 2023-02-22 13:59
The issue came from me. I followed the instructions of the README.md and tested with the official demo app: `sudo ctr run --rm --runtime=io.containerd.wasmedge.v1 ghcr.io/containerd/runwasi/wasi-demo-app:latest testwasm /wasi-demo-app.wasm echo 'hello'`
Same problem for wasmedge and wasmtime runtimes. No additional changes have been made.

@rumpl also `sudo ctr run --rm --runtime=io.containerd.wasmedge.v1 --platform=wasi/wasm docker.io/secondstate/rust-example-hello:latest test` hang - at the first execution!

**Comment by devigned** [comment] 2023-02-22 15:11
> @devigned I have not, can you point me to the source code of that image please? Trying to run this with docker gives me an error, I don't have a VM or a linux machine I could test this on right now
> 
> ```
> $ docker pull ghcr.io/containerd/runwasi/wasi-demo-app:latest
> Error response from daemon: failed to resolve reference "ghcr.io/containerd/runwasi/wasi-demo-app:latest": failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
> ```

I think the demo source is [here](https://github.com/containerd/runwasi/blob/a2f86e43e8df4efece9ec4b3f9460421f450c8fc/crates/wasi-demo-app/src/main.rs).

**Comment by sboett-dev** [comment] 2023-03-13 14:07
I still could not find any workaround or fix. Here is a complete script how to reproduce the entire thing. I tested on a fresh EC2 instance (t2.medium with Ubuntu 22).
```
# fresh start
rm -rf runwasi
sudo ctr task kill --signal=SIGKILL testwasm || true
sudo ctr c rm testwasm || true
sudo ctr image rm ghcr.io/containerd/runwasi/wasi-demo-app:latest

# install wasmedge
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
sudo -E sh -c 'echo "$HOME/.wasmedge/lib" > /etc/ld.so.conf.d/libwasmedge.conf'
sudo ldconfig

# install dependencies
sudo apt install -y make clang
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
. "$HOME/.cargo/env" && rustup target add wasm32-wasi
wget https://github.com/containerd/containerd/releases/download/v1.6.13/containerd-1.6.13-linux-amd64.tar.gz
sudo tar Czxvf /usr/local containerd-1.6.13-linux-amd64.tar.gz
rm containerd-1.6.13-linux-amd64.tar.gz

# configure systemd
sudo wget https://raw.githubusercontent.com/containerd/containerd/main/containerd.service -P /usr/lib/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable --now containerd

# clone runwasi repo
git clone -n https://github.com/containerd/runwasi
cd runwasi
git checkout 67c6be5f64f49b24cd9f0699ac955778757b83e7

# build & install
. "$HOME/.cargo/env" && make build
sudo make install
make load
sudo ctr i ls

# run demo app
for i in {1..100}
do
    echo "test #$i"
    sudo ctr run --rm --runtime=io.containerd.wasmedge.v1 ghcr.io/containerd/runwasi/wasi-demo-app:latest testwasm /wasi-demo-app.wasm echo 'hello'
done
```
This will hang at the second execution.

**Comment by jprendes** [comment] 2023-05-18 14:52
I managed to reproduce it with `wasmedge` `0.11.2` and `runwasi` from `67c6be5f64f49b24cd9f0699ac955778757b83e7`. For me it doesn't consistently hang in the second run, but rather sporadically about 1 in 20 runs.

However, I can't reproduce it with the latest versions: `wasmedge` `0.12.1` and `runwasi` from `main`.

@sboett-dev could you try with latest the versions?

**Comment by sboett-dev** [comment] 2023-05-18 16:14
@jprendes Thank you! I am currently on vacation but I will try it out asap!

**Comment by CaptainVincent** [comment] 2023-05-21 04:42
🤔 Hi, did I miss anything? When I last noticed, this issue had the same behavior in both the shim of Wasmedge and Wasmtime. If that's the case, this upgrade should not be helpful for it, but it's possible that other modifications during this time may have fixed the underlying problem. It is still worth revalidating once again. Thank you.

**Comment by jprendes** [comment] 2023-05-22 11:33
@CaptainVincent I suspect some change in `runwasi` since [this message](https://github.com/containerd/runwasi/issues/70#issuecomment-1466211808) has fixed the underlying issue.
I mentioned both versions because newer `runwasi` requires newer `wasmedge`.
Maybe bisecting could help find where exactly the fix happened.

**Comment by sboett-dev** [comment] 2023-07-26 11:36
I just tried it out again with the current master. I can confirm that it hangs spontaneously after 50-200 runs. You also cannot kill the hanging container with `sudo ctr c remove wasmtest`. That was possible after a reboot though.

**Comment by ipuustin** [comment] 2023-07-26 13:16
Ran the test for 1000 iterations on Fedora 38, no hangs. Can you see with gdb or similar where the process is stuck? Is there anything in system or container logs?

**Comment by jprendes** [comment] 2023-10-27 15:05
> I just tried it out again with the current master. I can confirm that it hangs spontaneously after 50-200 runs.

I believe this could have been the same issue as #347.

Is anyone still experiencing any issues with sporadic hangs?
Or can we close this issue?

**Comment by Mossaka** [comment] 2023-11-03 20:07
I am happy to close this issue. If anyone still experiencing similar issues, feel free to re-open it.

**Closed by Mossaka** 2023-11-03 20:07 UTC
