### ISSUE TITLE
Update wasmtime deps to latest version (6.x)

### ISSUE THREAD

**Issue by jsturtevant** [containerd/runwasi#72] opened 2023-02-22 20:10 UTC
I tried to update the `wasmtime` dep to the latest and found that `runwasmedge` is blocking the upgrade do to a dep on `wasmtime-fiber`:

```
[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/jstur/projects/runwasi/Cargo.toml, Some(Version { major: 1, minor: 67, patch: 1 }): Failed to run `"cargo" "metadata" "--format-version" "1" "--features" "generate_bindings" "--manifest-path" "/home/jstur/projects/runwasi/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error:     Blocking waiting for file lock on package cache
    Updating crates.io index
error: failed to select a version for `wasmtime-fiber`.
    ... required by package `runwasmedge v0.1.0 (/home/jstur/projects/runwasi/crates/wasmedge)`
versions that meet the requirements `^2.0` are: 2.0.2, 2.0.1, 2.0.0

the package `wasmtime-fiber` links to the native library `wasmtime-fiber-shims`, but it conflicts with a previous package which links to `wasmtime-fiber-shims` as well:
package `wasmtime-fiber v6.0.0`
    ... which satisfies dependency `wasmtime-fiber = "=6.0.0"` of package `wasmtime v6.0.0`
    ... which satisfies dependency `wasmtime = "^6.0"` of package `runwasmtime v0.1.0 (/home/jstur/projects/runwasi/crates/wasmtime)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='wasmtime-fiber' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `wasmtime-fiber` which could resolve this conflict


[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/jstur/projects/runwasi/Cargo.toml, Some(Version { major: 1, minor: 67, patch: 1 }): Failed to run `"cargo" "metadata" "--format-version" "1" "--features" "generate_bindings" "--manifest-path" "/home/jstur/projects/runwasi/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error:     Updating crates.io index
error: failed to select a version for `wasmtime-fiber`.
    ... required by package `runwasmedge v0.1.0 (/home/jstur/projects/runwasi/crates/wasmedge)`
versions that meet the requirements `^2.0` are: 2.0.2, 2.0.1, 2.0.0

the package `wasmtime-fiber` links to the native library `wasmtime-fiber-shims`, but it conflicts with a previous package which links to `wasmtime-fiber-shims` as well:
package `wasmtime-fiber v6.0.0`
    ... which satisfies dependency `wasmtime-fiber = "=6.0.0"` of package `wasmtime v6.0.0`
    ... which satisfies dependency `wasmtime = "^6.0"` of package `runwasmtime v0.1.0 (/home/jstur/projects/runwasi/crates/wasmtime)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='wasmtime-fiber' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `wasmtime-fiber` which could resolve this conflict
```

It seems since each of these shims is a separate binary we should be able have different dependencies but the current way it is set up doesn't allow for this.

I think we either need wasmedge to update its dep at https://github.com/WasmEdge/WasmEdge/blob/e27198bf674c18989111c2075758c2ee147556fe/bindings/rust/wasmedge-sys/Cargo.toml#L24 or need to re-organize the packages to allow for the binaries to link files seperately (not 100% sure how to do this)

**Comment by devigned** [comment] 2023-02-22 20:12
@CaptainVincent do you think wasmtime-fiber is a candidate for update in WasmEdge?

**Comment by jsturtevant** [comment] 2023-02-22 20:20
fyi - this also blocks updating the `cap-std` = "0.26" since it requires a newer version of `wasmtime`

**Comment by Mossaka** [comment] 2023-02-22 20:59
@jsturtevant this will resolve it https://github.com/WasmEdge/WasmEdge/pull/2306

**Comment by jsturtevant** [comment] 2023-02-24 16:38
@Mossaka I see you had a similar question to mine about organization of the project:

> Question: with the monthly release of wasmtime major version, how will projects like [runwasi](https://github.com/containerd/runwasi) that embeds both wasmtime and wasmedge use the newest version of wasmtime? IT seems like if the async feature is enabled, wasmedge will be depended on a crate from wasmtime, and thus cause cargo to not be able to resolve transient package versions like wasmtime-fiber

Since wasitime and wasmedge are seperate binaires (with different runtimes) I would expect their dependencies to be able to be different.  Is there another way we could organize the project to enable this?

**Comment by Mossaka** [comment] 2023-02-27 20:16
> Is there another way we could organize the project to enable this?

We are sharing wasmtime and wasmedge in the same workspace so that they produce a single `Cargo.lock` file and this is the cause of the issue iiuc. One solution is that we split the two into two individual workspaces. Another solution is we use [conditional compilation ](https://doc.rust-lang.org/reference/conditional-compilation.html) to put wasmtime as the default feature. I'd prefer the first one.

**Comment by cpuguy83** [comment] 2023-02-28 00:00
Splitting it out of the workspace seems good.

**Comment by CaptainVincent** [comment] 2023-04-10 18:17
> @CaptainVincent do you think wasmtime-fiber is a candidate for update in WasmEdge?

I apologize for not noticing the message earlier. The past few weeks were the peak period of our consecutive holidays. I have noticed that wasmtime has been upgraded to version 7.0 in issue #94, and it seems that the conflict issue has been resolved, right? However, is there still a need to upgrade the wasmedge's dependencies for compatibility? We are actively preparing for the release of WasmEdge version 0.12, which includes some plugin-related features could be used in runwasi. If there is a need to upgrade the crates for compatibility, please let me know, and I will ask our team members to handle it.

**Comment by cpuguy83** [comment] 2023-04-10 18:32
We turned off async support in wasmtime so that we don't need to link to the offending crate except for wasmedge.
So its working without needing to change wasmedge, but it is not ideal, and seems like it would be somewhat difficult to keep in sync regardless.
I spoke with the folks on the wasmtime project and they suggested wasmedge fork the crate and give it a different name.

**Comment by CaptainVincent** [comment] 2023-04-11 03:25
Copy that. I will provide feedback to our Rust SDK team and see if we can handle it together before version 0.12. Thanks.

**Comment by Mossaka** [comment] 2023-06-20 20:29
Close this one as it is out-of-date.

**Closed by Mossaka** 2023-06-20 20:29 UTC
